# Generated by Django 6.0.1 on 2026-01-15 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='escrow_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='escrow_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('wave', 'Wave'), ('card', 'Carte bancaire'), ('delivery', 'Paiement à la livraison')], default='orange_money', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('preparing', 'En préparation'), ('delivering', 'En livraison'), ('delivered', 'Livré'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='artisan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
