# Generated by Django 6.0.1 on 2026-01-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.IntegerField(default=1)),
                ('category', models.CharField(max_length=100)),
                ('is_limited_edition', models.BooleanField(default=False)),
                ('limited_quantity', models.IntegerField(blank=True, null=True)),
                ('origin', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('video_url', models.FileField(blank=True, null=True, upload_to='product_videos/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('average_rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
    ]
